#!/usr/bin/env bash
# Infinite loop that prints "To infinity and beyond" and responds to SIGTERM

term_handler() {
    echo "I am invincible!!!"
}

trap term_handler SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
