#!/usr/bin/env bash
# This script displays "I am invincible!!!" when receiving SIGTERM but doesn't terminate

# إعداد معالج إشارة SIGTERM
term_handler() {
    echo "I am invincible!!!"
}

# تسجيل معالج الإشارة
trap term_handler SIGTERM

# استمر في التنفيذ للأبد
echo "PID: $$ - Waiting for SIGTERM..."
while true
do
    # استخدم read -t للسماح باستقبال الإشارات
    read -t 1000
done
